# Generated by Django 5.0.3 on 2024-03-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_alter_useraccount_fullname'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
    ]
